// <auto-generated />
using FXY_NetCore_DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FXY_NetCore_DbContext.Migrtion.MySqlMigrations
{
    [DbContext(typeof(DefaultMySqlContext))]
    partial class DefaultMySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FXY_NetCore_DbEntity.Student", b =>
                {
                    b.Property<string>("UUID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BirthPlace");

                    b.Property<string>("Name");

                    b.HasKey("UUID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("FXY_NetCore_DbEntity.Teacher", b =>
                {
                    b.Property<string>("UUID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BirthPlace");

                    b.Property<string>("Name");

                    b.HasKey("UUID");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
