// <auto-generated />
using FXY_NetCore_DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FXY_NetCore_DbContext.Migrations
{
    [DbContext(typeof(DefaultMySqlContext))]
    [Migration("20190405110054_INIT")]
    partial class INIT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FXY_NetCore_DbEntity.Student", b =>
                {
                    b.Property<string>("UUID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BirthPlace");

                    b.Property<string>("Name");

                    b.HasKey("UUID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("FXY_NetCore_DbEntity.Teacher", b =>
                {
                    b.Property<string>("UUID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BirthPlace");

                    b.Property<string>("Name");

                    b.HasKey("UUID");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
